title:    CyVerse UK at Warwick
tagline:  About our applications

author:
  name:   CyVerse UK Team at Warwick
  url:    mailto:info@cyverse.warwick.ac.uk

gems:
  - jekyll-sitemap
  - jemoji

theme:    jekyll-theme-cayman
